#!/usr/bin/env bash

set -e

## Add build essentials
sudo apt install build-essential -y

## Add Java JDK LTS
sudo apt install openjdk-11-jdk -y

sudo apt install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
	nfs-common \
    software-properties-common -y -q


