#!/usr/bin/env bash

set -e

# Install general utilities
sudo apt-get install -y -qq \
	git htop lame net-tools flatpak audacity \
	openssh-server sshfs simplescreenrecorder nano \
	vlc gthumb gnome-tweaks ubuntu-restricted-extras \
	thunderbird ffmpeg ufw gnome-tweak-tool spell synaptic 

# Install drivers
sudo apt-get install -y \
	oem-somerville-melisa-meta \
	libfprint-2-tod1-goodix \
	oem-somerville-meta \
	tlp-config

# Install fusuma for handling gestures
sudo gpasswd -a $USER input
sudo apt-get install libinput-tools xdotool ruby -y -qq
sudo gem install --silent fusuma

# Install Howdy for facial recognition
sudo add-apt-repository ppa:boltgolt/howdy -y > /dev/null 2>&1
sudo apt-get update -qq
sudo apt-get install -y howdy

# Remove packages:
sudo apt remove rhythmbox -y -q

# Add Flatpak support:
sudo apt install gnome-software-plugin-flatpak -y

sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

