#!/usr/bin/env bash

set -e

# Install general utilities
sudo apt-get install -y -qq \
	git htop lame net-tools flatpak audacity \
	openssh-server sshfs simplescreenrecorder nano \
	vlc gthumb gnome-tweaks ubuntu-restricted-extras \
	thunderbird ffmpeg ufw gnome-tweak-tool spell synaptic 

# Install drivers
sudo apt-get install -y \
	oem-somerville-melisa-meta \
	libfprint-2-tod1-goodix \
	oem-somerville-meta \
	tlp-config

# Install fusuma for handling gestures
sudo gpasswd -a $USER input
sudo apt-get install libinput-tools xdotool ruby -y -qq
sudo gem install --silent fusuma

# Install Howdy for facial recognition
sudo add-apt-repository ppa:boltgolt/howdy -y > /dev/null 2>&1
sudo apt-get update -qq
sudo apt-get install -y howdy

# Remove packages:
sudo apt remove rhythmbox -y -q

# Add Flatpak support:
sudo apt install gnome-software-plugin-flatpak -y

sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo


## Update python essentials
sudo apt-get install -y python3 python3-pip 
sudo python3 -m pip install -U pip setuptools wheel
python3 -m pip install --user black

## Add build essentials
sudo apt install build-essential -y

## Add Java JDK LTS
sudo apt install openjdk-11-jdk -y

sudo apt install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common -y -q

curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /tmp/packages.microsoft.gpg
sudo install -o root -g root -m 644 /tmp/packages.microsoft.gpg /usr/share/keyrings/
sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'


curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable" > /dev/null 2>&1
sudo apt update -qq && sudo apt install docker-ce docker-ce-cli docker-compose containerd.io code -y

## Post installation for docker

sudo groupadd -f docker
sudo usermod -aG docker $USER

## Post installation for code (sensible defaults)
code --install-extension ms-python.python
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension eamodio.gitlens
code --install-extension ms-azuretools.vscode-docker


## Install Go
wget https://golang.org/dl/go1.16.linux-amd64.tar.gz -O /tmp/go1.16.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf /tmp/go1.16.linux-amd64.tar.gz

if ! grep -qF "export PATH=\$PATH:/usr/local/go/bin" /etc/profile; then
  sudo sh -c 'echo "export PATH=\$PATH:/usr/local/go/bin" >> /etc/profile'
fi


## Install dotnet-core sdk + runtime
wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb

sudo apt-get update
sudo apt-get install -y dotnet-sdk-5.0
sudo apt-get install -y aspnetcore-runtime-5.0


## Node.JS + Yarn Install
echo "Installing Node 14 JS LTS"
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt-get install -y nodejs 
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list 
sudo apt-get update -qq && sudo apt-get install -y yarn


## Install snaps
snaps=(discord gimp krita insomnia postman doctl aws-cli jupyter pop-themes lxd) 
snaps_classic=(ripgrep slack)
for s in "${snaps[@]}"; do
	sudo snap install $s
done
for s in "${snaps_classic[@]}"; do
	sudo snap install $s --classic
done


## Install flatpaks
flatpaks=(Okular Zeal Obsidian HomeBank HandBrake Steam)
for f in "${flatpaks[@]}"; do
	sudo flatpak install $f
done

## Gotta reboot now:
sudo apt update -qq && sudo apt upgrade -y && sudo apt autoremove -y


