#!/usr/bin/env bash

set -e

src_dir=$HOME/.local/src

sudo apt-get update && \
	sudo apt-get install -y timeshift btrfs-progs

git clone \
	https://github.com/Antynea/grub-btrfs.git $src_dir/grub-btrfs

cd $src_dir/grub-btrfs
sudo make install

git clone \
	https://github.com/wmutschl/timeshift-autosnap-apt.git $src_dir/timeshift-autosnap-apt
cd $src_dir/timeshift-autosnap-apt
sudo make install

